include: "rules/00_common.smk"
include: "rules/01_qc.smk"
include: "rules/02_map_reads.smk"
include: "rules/03_variant_calling_haplotypecaller.smk"
include: "rules/04_variant_validation.smk"

rule all:
    input:
        expand("{outpath}/01_multiqc/multiqc_report_fq.html", outpath=outpath),
        expand("{outpath}/02_map/multiqc_report_map.html", outpath=outpath),
        expand("{outpath}/03_variants/haplotypecaller/summary.txt", outpath=outpath),
        expand("{outpath}/04_validation/summary.txt", outpath=outpath)