#-------------------
## container
##-------------------
##-------01_qc-------
bedtools_2.31.1: docker://junhuili/terra_bedtools:2.31.1--h13024bc_3
fastp_0.22.0: docker://junhuili/fastp:latest
fastqc_0.11.9: docker://biocontainers/fastqc:v0.11.9_cv8
multiqc_1.22.3: docker://multiqc/multiqc:latest

##-------02_map-------
STAR_2.7.10a: docker://alexdobin/star:2.7.10a_alpha_220506
samtools_1.20: docker://junhuili/terra_samtools:1.20
sambamba_1.0.1: docker://junhuili/sambamba:1.0.1
terra_deeptools_0.1: docker://junhuili/terra_deeptools:0.1
gatk_4.6.1.0: docker://broadinstitute/gatk:4.6.1.0
gatk_4.1.8.1: docker://broadinstitute/gatk:4.1.8.1
py_3.21: docker://python:alpine3.21

##-------03_variant_calling-------
vcftools_0.1.16: docker://biocontainers/vcftools:v0.1.16-1-deb_cv1
bcftools_1.9: docker://biocontainers/bcftools:v1.9-1-deb_cv1

deepsomatic_1.8.0: /pi/michael.lodato-umw/junhui.li11-umw/BautistaSotelo_Cesar/20201130_MosaicVariant_DNA/00script/00_pipeline/mosaic_variants_calling_largeinput/workflow/envs/deepsomatic_1.8.0.sif
deepvariant_1.8.1: docker://ksinghal28/deepvariant:1.8.1
terra_r: docker://junhuili/terra_r:latest
python_alpine3.21: docker://python:alpine3.21
variantqc_1.3.87: docker://junhuili/discvrseq:1.3.87


##-------04_filter-------
terra_py_tools: docker://junhuili/terra_py_tools:latest
terra_perl_anno: docker://junhuili/terra_perl_anno:latest

##-------05_spliceAI-------
#spliceai_1.3.1: docker://cmgantwerpen/spliceai_v1.3:full
spliceai_1.3.1: /pi/michael.lodato-umw/junhui.li11-umw/BautistaSotelo_Cesar/20201130_MosaicVariant_DNA/00script/00_pipeline/RNA_variants_calling/workflow/envs/spliceai_1.3.1.sif


