$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  resource:
    type: string
  units:
    type: string
  callers:
    type: array
    items:
      type: string
      enum: ["haplotypecaller", "deepvariant"]
  outpath:
    type: string
  ref_version:
    type: string
  reference:
    type: string
  interval:
    type: string
required:
  - resource
  - units
  - callers